### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [fja122/Website-project#1]
# Feedback

## Requirements:

1. Deployed website (using GitHub Pages): DONE
2. Public GitHub repository for your codebase: DONE
3. Usage of HTML & SCSS: DONE
4. Proper utilization of semantic HTML elements: DONE
5. Responsiveness (mobile-first) and built with accessibility in mind: NOT DONE
6. Highly readable code (well-named and correctly indented): NOT DONE

## Score

[Marking Scheme](https://github.com/nology-tech/Verde-Course-Resources/blob/main/student-resources/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 20 / 50  |
| Responsiveness       | 5 / 15   |
| Code Knowledge & Use | 10 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 5 / 10   |
| Total Score          | 50 / 110 |

### Positive

- Nice, You have started to use Semantic HTML elements.
- Well done in breaking up your SCSS into different files, aiding better management as you add more content.
- Demonstrated understanding of covered topics—keep utilizing SCSS and you are starting to use grid, and flex.

### Constructive

- Currently, the project falls below the expected standard due to:

  - Ineffective use of Grid and Flex.
  - Heavy reliance on Figma styles for width and height.
    - This is causing issues with responsiveness.
  - Lack of responsiveness, absence of media queries.
  - Unable to implement BEM naming conventions.

- Concerns arise as we weren't aware of your challenges in applying these concepts.

  - We're available to assist, but communication is key.

- We're committed to supporting you but require additional time to complete this project.

- Initial cleanup steps:

  - Rename the following files:

    - `variables.scss` to `_variables.scss`
    - `techskills.scss` to `_tech-skills.scss`
    - These are partial files and should start with `_` to prevent CSS file creation on compilation.

  - Delete the following files:
    - `_techskills.css`, `techskills.css`, `techskills.css.map`, `styles.css`, `styles.css.map`, `variables.css`, `variables.css.map`
    - These autogenerated files are unnecessary.

- HTML adjustments needed:

  - Rearrange your HTML: Move the `nav` above the `header-container`.

- Eliminate references in your SCSS similar to the code snippet below as they may cause issues.

```scss
.aboutme {
  // For better responsiveness, avoid setting width and height unless necessary.
  // If specifying width or height, refrain from using hardcoded values like 39px or 151px.
  width: 151px;
  height: 39px;
  // Avoid using top, left, right, and bottom for absolute positioning.
}
```

- Upon completion, let's regroup, devise a plan, and utilize grid, flex, and media queries to finalize this project, which currently requires additional work.

---
